server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/MEMBERMANAGE?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
